### ISSUE TITLE
오늘의 메뉴 반복 질문시 text에 메뉴 누적됨

### ISSUE THREAD

**Issue by ksm0076** [greg1028/OSS#67]
![캡처](https://user-images.githubusercontent.com/60387895/206497749-a5b22981-8d8f-4269-838d-1fc64b6723ef.PNG)

**Comment by greg1028** [comment]
고쳤어요
![image](https://user-images.githubusercontent.com/83526669/206697124-6a525d4b-94e1-45e1-9e6f-82848105bf59.png)
